import {AbsoluteFill,Sequence,useCurrentFrame,staticFile} from 'remotion';import {Audio} from '@remotion/media';import {loadFont} from '@remotion/fonts';
import {C} from './ui';import {PixelDuck} from './PixelDuck';import timeline from './timeline.json';import captions from './captions.json';
import {Hook} from './scenes/Hook';import {Repo} from './scenes/Repo';import {Demo} from './scenes/Demo';import {Booking} from './scenes/Booking';import {Onboarding} from './scenes/Onboarding';import {Interact} from './scenes/Interact';import {Limit} from './scenes/Limit';import {Cta} from './scenes/Cta';
loadFont({family:'Calling',url:staticFile('regular.otf'),weight:'400'});loadFont({family:'Calling',url:staticFile('bold.otf'),weight:'700'});
const views=[Hook,Repo,Demo,Booking,Onboarding,Interact,Limit,Cta];
export const Video=({cover=false}:{cover?:boolean})=>{const f=useCurrentFrame(),t=f/30;const cap=captions.find(c=>t>=c.start&&t<c.end);const ix=(timeline.scenes.findIndex(s=>t>=s.start&&t<s.end)<0?6:timeline.scenes.findIndex(s=>t>=s.start&&t<s.end));const gridX=(f*0.42)%52;const gridY=(f*0.24)%52;const glowX=Math.sin(f/92)*250;const glowY=Math.cos(f/117)*180;return <AbsoluteFill style={{backgroundColor:C.blue,color:C.ink,fontFamily:'Calling',backgroundImage:'linear-gradient(rgba(155,214,208,.14) 2px,transparent 2px),linear-gradient(90deg,rgba(155,214,208,.14) 2px,transparent 2px)',backgroundSize:'52px 52px',backgroundPosition:`${gridX}px ${gridY}px`,overflow:'hidden'}}>
<div style={{position:'absolute',inset:-280,pointerEvents:'none',background:'radial-gradient(circle,rgba(91,214,191,.20) 0%,rgba(35,111,138,.11) 24%,transparent 58%)',transform:`translate3d(${glowX}px,${glowY}px,0)`,filter:'blur(20px)',opacity:.9}}/>
<div style={{position:'absolute',inset:-220,pointerEvents:'none',background:'radial-gradient(circle,rgba(255,185,92,.13) 0%,transparent 42%)',transform:`translate3d(${-glowY*.55}px,${glowX*.35}px,0)`,filter:'blur(30px)',opacity:.8}}/>
<Audio src={staticFile('voice.wav')}/><Audio src={staticFile('musicbg.mp3')} volume={1}/>
<div style={{position:'absolute',top:164,left:80,width:850,border:`3px solid ${C.border}`,background:C.paper,borderRadius:13,padding:'14px 20px',fontSize:32,lineHeight:1.28,boxShadow:`5px 5px 0 ${C.border}25`,display:'flex',alignItems:'center',gap:12,whiteSpace:'nowrap'}}><b>WindiStudio -</b><span>Sử Dụng AI Hiệu Quả</span></div>
<div style={{position:'absolute',top:300,left:80,fontSize:26,letterSpacing:3}}>REPO ĐÁNG THỬ / 001 <span style={{color:C.pink}}>●</span> ARCHIFY</div>
{timeline.scenes.map((s,i)=>{const Scene=views[i];const floatX=Math.sin((f+i*29)/52)*4;const floatY=Math.sin((f+i*41)/38)*13;const tilt=Math.sin((f+i*23)/71)*.75;return <Sequence key={s.id} from={s.fromFrame} durationInFrames={s.durationInFrames+(i===timeline.scenes.length-1?18:0)}><div style={{position:'absolute',top:368,left:80,width:850,transform:`translate3d(${floatX}px,${floatY}px,0) rotate(${tilt}deg)`,willChange:'transform'}}><Scene/></div></Sequence>})}
{cap&&!cover&&<div style={{position:'absolute',top:1430,left:80,width:850,display:'flex',justifyContent:'center'}}><div style={{background:C.paper,border:`3px solid ${C.border}`,boxShadow:`5px 5px 0 ${C.border}25`,borderRadius:12,padding:'18px 25px',fontSize:49,lineHeight:1.3,textAlign:'center',fontWeight:700,maxWidth:850}}>{cap.text}</div></div>}
<div style={{position:'absolute',left:80,top:1640,width:850,height:12,border:`2px solid ${C.border}`,borderRadius:6,background:C.paper,overflow:'hidden'}}><div style={{width:`${100*f/timeline.frames}%`,height:'100%',background:C.pink}}/></div>
<div style={{position:'absolute',left:80,top:1682,width:850,fontSize:27,display:'flex',justifyContent:'space-between'}}><span>WINDISTUDIO / AI TOOLBOX</span><span>{String(ix+1).padStart(2,'0')} / {String(timeline.scenes.length).padStart(2,'0')}</span></div>
{(f<timeline.scenes[0].durationInFrames||f>timeline.scenes[timeline.scenes.length-1].fromFrame)&&<div style={{position:'absolute',left:780+Math.sin(f/20)*25,top:1740+Math.sin(f/12)*10,transform:'scale(.9)'}}><PixelDuck/></div>}
</AbsoluteFill>};
