import Link from 'next/link';
import {ArrowUpRight,ArrowRight,Image,Link2,Sparkles} from 'lucide-react';
import {WorkflowArcade} from './workflow-arcade';
import {FloatingDetails} from './ambient-motion';
export function WorkflowHero({detail=false}:{detail?:boolean}) {
  return <section className="workflow-hero" aria-labelledby="workflow-title">
    <div className="workflow-copy"><div className="workflow-eyebrow"><span/> WINDI STUDIO / VIDEO WORKFLOW</div>
      <h1 id="workflow-title">Bạn chốt hướng.<br/>Windi làm <em>video.</em></h1>
      <p>Một video đáng xem không bắt đầu từ nút render.<br/>Nó bắt đầu từ một hướng kể đủ đúng để người ta muốn xem tiếp.</p>
      <div className="workflow-actions"><Link className="retro-button primary" href={detail?'#kit-purchase':'/video-kits'}>{detail?'Sở hữu Video Kits':'Bắt đầu với Video Kits'} <ArrowUpRight size={18}/></Link><Link className="workflow-voice-link" href="/voice-studio">Nghe thử Voice Studio <ArrowRight size={16}/></Link></div>
      <div className="workflow-proof"><span>CHỐT Ý TƯỞNG</span><span>CHỌN LAYOUT</span><span>DUYỆT KỊCH BẢN</span></div>
      <div className="workflow-note"><span className="workflow-note-arrow">↗</span><span>Không đốt quota vào một hướng chưa chốt.<br/><strong>Bạn duyệt ba điểm quan trọng. Windi lo phần còn lại.</strong></span></div>
    </div>
    <div className="workflow-machine-wrap"><FloatingDetails kind="kit"/><WorkflowArcade/></div>
  </section>;
}
export function HomeVoiceFeature(){return <section className="home-voice-feature" aria-labelledby="home-voice-title"><div><span className="eyebrow">02 / WINDI VOICE STUDIO</span><h2 id="home-voice-title">Đừng chỉ đọc.<br/><em>Hãy khiến người ta nghe tiếp.</em></h2><p>Tạo hoặc clone giọng tiếng Việt có cảm xúc theo ngữ cảnh. Nghe thử, chọn chất giọng, rồi đưa thẳng vào video của bạn.</p><Link className="retro-button" href="/voice-studio">Khám phá Voice Studio <ArrowUpRight size={18}/></Link></div><div className="home-voice-player"><div className="home-voice-player-top"><span className="on-air-dot"/> WINDI RADIO <span>01 / CHỮA LÀNH</span></div><div className="home-voice-wave" aria-hidden="true">{Array.from({length:40},(_,i)=><i key={i} style={{height:`${16+Math.abs(Math.sin(i*1.7)*Math.cos(i*.3))*74}%`}}/>)}</div><blockquote>“Có những ngày, chúng ta chỉ cần<br/>chậm lại một chút…”</blockquote><audio controls preload="none" aria-label="Nghe mẫu giọng Chữa Lành" src="/voice-comparisons/clone-pro/chua%20lanh.wav"/><p>Ấm áp · chậm rãi · giàu khoảng lặng</p></div></section>;}
export function HomeLayouts(){return <section className="home-layouts" aria-labelledby="home-layouts-title"><div className="home-layouts-heading"><span className="eyebrow">03 / CHỌN PHONG CÁCH</span><h2 id="home-layouts-title">Một câu chuyện.<br/>Một cảm giác rất khác.</h2><Link href="/video-kits#kit-layouts">Chọn cách kể <ArrowUpRight size={16}/></Link></div><Link href="/video-kits#kit-layouts" className="home-layout-paper"><span>01 / PAPER EDITORIAL</span><strong>Biến điều<br/>phức tạp thành<br/><em>thứ ai cũng hiểu.</em></strong><span>Rõ ý. Có nhịp. Không hề nhạt.</span></Link><Link href="/video-kits#kit-layouts" className="home-layout-cinema"><span>02 / DARK CINEMATIC</span><div className="layout-orbit" aria-hidden="true"/><strong>Khi mỗi cảnh<br/>đều phải khiến<br/>người ta dừng lại.</strong><span>Điện ảnh. Dày cảm xúc. Có dư âm.</span></Link></section>;}
export function HomeConnectFeature(){return <section className="home-connect-feature" aria-labelledby="home-connect-title"><div className="home-connect-copy"><span className="eyebrow">04 / WINDI CONNECT</span><h2 id="home-connect-title">Đừng để ý tưởng<br/><em>chết trong một tab.</em></h2><p>Prompt đã chốt đi thẳng từ workflow sang ChatGPT hoặc Google Flow của bạn. Ảnh về đúng cảnh, đúng project, sẵn sàng cho nhịp dựng kế tiếp.</p><Link className="retro-button primary" href="/video-kits">Xem Windi Connect hoạt động <ArrowUpRight size={18}/></Link></div><div className="home-connect-console" aria-label="Windi Connect đưa ảnh vào đúng cảnh của video"><div className="home-connect-console-bar"><span><i/><i/><i/></span><b>WINDI CONNECT</b><small>SẴN SÀNG</small></div><div className="home-connect-route"><div className="connect-project"><Image size={19}/><span>Cảnh 04</span><small>prompt đã chốt</small></div><Link2 className="connect-link" size={22} aria-hidden="true"/><div className="connect-provider"><Sparkles size={18}/><strong>ChatGPT</strong><span>hoặc Google Flow</span></div></div><div className="home-connect-result"><span>ẢNH ĐÃ THÊM</span><b>Cảnh 04 đã sẵn sàng để dựng</b><i>✓ Không cần chép file thủ công</i></div></div></section>;}
