import path from 'node:path';
import net from 'node:net';
import {spawn, type ChildProcess} from 'node:child_process';
import {createHash, randomUUID} from 'node:crypto';
import {createReadStream} from 'node:fs';
import {lstat, open, readFile, readdir, rename, unlink, writeFile} from 'node:fs/promises';
import {loadWorkflow} from './workflow.ts';
import {safeFile,safeOutput} from './project.ts';

type PostStatus='awaiting_approval'|'approved'|'submitting'|'action_required'|'outcome_unknown'|'verified';
type PostRecord={schemaVersion:1;workflowId:string;render:string;sha256:string;bytes:number;caption:string;account:string;privacy:'SELF_ONLY';approvalCode:string;status:PostStatus;approvedAt:string|null;attemptedAt:string|null;postUrl:string|null;reason:string|null};
const recordDir=(root:string)=>path.join(root,'.windi','tiktok-posts');
const recordPath=(root:string,code:string)=>{if(!/^[a-f0-9]{16}$/.test(code))throw new Error('INVALID_TIKTOK_APPROVAL_CODE');return path.join(recordDir(root),`${code}.json`);};
const normalizeAccount=(value:string)=>{const account=value.trim().replace(/^@/,'');if(!/^[\w.]{2,30}$/.test(account))throw new Error('INVALID_TIKTOK_ACCOUNT');return account;};
const hashFile=async(file:string)=>new Promise<string>((resolve,reject)=>{const hash=createHash('sha256');const stream=createReadStream(file);stream.on('data',chunk=>hash.update(chunk));stream.on('error',reject);stream.on('end',()=>resolve(hash.digest('hex')));});
async function save(root:string,record:PostRecord){const file=await safeOutput(root,path.relative(root,recordPath(root,record.approvalCode)));const temporary=`${file}.${randomUUID()}.tmp`;await writeFile(temporary,`${JSON.stringify(record,null,2)}\n`,{mode:0o600});await rename(temporary,file);return record;}
async function load(root:string,code:string):Promise<PostRecord>{const record=JSON.parse(await readFile(await safeFile(root,recordPath(root,code)),'utf8')) as PostRecord;if(record.schemaVersion!==1||record.privacy!=='SELF_ONLY'||record.approvalCode!==code)throw new Error('INVALID_TIKTOK_POST_RECORD');return record;}
async function checkedRender(root:string){const state=await loadWorkflow(root);if(state.stage!=='complete'||!state.artifacts.render||!state.artifacts.qa)throw new Error('VIDEO_QA_REQUIRED');const file=await safeFile(root,path.join(root,state.artifacts.render));const qa=JSON.parse(await readFile(await safeFile(root,path.join(root,state.artifacts.qa)),'utf8')) as {passed?:unknown;outputs?:{render?:unknown}};if(qa.passed!==true||path.resolve(String(qa.outputs?.render||''))!==file)throw new Error('VIDEO_QA_REQUIRED');if(path.extname(file).toLowerCase()!=='.mp4')throw new Error('TIKTOK_MP4_REQUIRED');const info=await lstat(file);if(info.size<1024)throw new Error('TIKTOK_MP4_INVALID');return {state,file,bytes:info.size,sha256:await hashFile(file)};}
export async function prepareTikTokPost(root:string,caption:string,account:string){
  const video=await checkedRender(root);const cleanCaption=caption.trim();if(!cleanCaption||cleanCaption.length>2200)throw new Error('INVALID_TIKTOK_CAPTION');const handle=normalizeAccount(account);
  const material=`${video.state.workflowId}\n${video.sha256}\n${cleanCaption}\n${handle}\nSELF_ONLY`;
  const approvalCode=createHash('sha256').update(material).digest('hex').slice(0,16);
  const existing=await load(root,approvalCode).catch((error:NodeJS.ErrnoException)=>{if(error.message==='PROJECT_FILE_NOT_FOUND')return null;throw error;});
  if(existing)return existing;
  const names=await readdir(recordDir(root)).catch((error:NodeJS.ErrnoException)=>{if(error.code==='ENOENT')return [];throw error;});
  for(const name of names){if(!/^[a-f0-9]{16}\.json$/.test(name))continue;const prior=await load(root,name.slice(0,16));if(prior.sha256===video.sha256&&['submitting','outcome_unknown','verified'].includes(prior.status))throw new Error('TIKTOK_VIDEO_ALREADY_ATTEMPTED');}
  return save(root,{schemaVersion:1,workflowId:video.state.workflowId,render:path.relative(root,video.file),sha256:video.sha256,bytes:video.bytes,caption:cleanCaption,account:handle,privacy:'SELF_ONLY',approvalCode,status:'awaiting_approval',approvedAt:null,attemptedAt:null,postUrl:null,reason:null});
}
export async function approveTikTokPost(root:string,approvalCode:string){
  const record=await load(root,approvalCode);
  if(record.status!=='awaiting_approval'&&record.status!=='action_required')throw new Error('TIKTOK_POST_NOT_AWAITING_APPROVAL');
  const video=await checkedRender(root);if(video.state.workflowId!==record.workflowId||video.sha256!==record.sha256||video.bytes!==record.bytes)throw new Error('TIKTOK_VIDEO_CHANGED');
  record.status='approved';record.approvedAt=new Date().toISOString();record.reason=null;return save(root,record);
}
export async function tikTokPostStatus(root:string,approvalCode:string){const record=await load(root,approvalCode);return {...record,video:path.join(root,record.render)};}

async function checkedCookieFile(file:string){const info=await lstat(file);if(!info.isFile()||info.isSymbolicLink())throw new Error('TIKTOK_COOKIE_FILE_INVALID');if(process.platform!=='win32'&&(info.mode&0o077)!==0)throw new Error('TIKTOK_COOKIE_FILE_PERMISSIONS');const content=await readFile(file,'utf8');if(!content.includes('tiktok.com'))throw new Error('TIKTOK_COOKIE_FILE_MISSING_DOMAIN');return file;}
async function freePort(){const server=net.createServer();await new Promise<void>((resolve,reject)=>server.once('error',reject).listen(0,'127.0.0.1',resolve));const address=server.address();if(!address||typeof address==='string')throw new Error('LIGHTPANDA_PORT_UNAVAILABLE');await new Promise<void>(resolve=>server.close(()=>resolve()));return address.port;}
const pause=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));
class Cdp {
  private next=0;
  private sessionId:string|undefined;
  private pending=new Map<number,{resolve:(value:any)=>void;reject:(error:Error)=>void}>();
  private socket:WebSocket;
  constructor(socket:WebSocket){this.socket=socket;socket.addEventListener('message',event=>{let message:any;try{message=JSON.parse(String(event.data));}catch{return;}if(typeof message.id!=='number')return;const waiting=this.pending.get(message.id);if(!waiting)return;this.pending.delete(message.id);message.error?waiting.reject(new Error(`LIGHTPANDA_CDP_${message.error.message}`)):waiting.resolve(message.result);});}
  send(method:string,params:Record<string,unknown>={}){return new Promise<any>((resolve,reject)=>{const id=++this.next;this.pending.set(id,{resolve,reject});this.socket.send(JSON.stringify({id,method,params,...(this.sessionId?{sessionId:this.sessionId}:{})}));setTimeout(()=>{if(this.pending.delete(id))reject(new Error(`LIGHTPANDA_CDP_TIMEOUT_${method}`));},20_000).unref();});}
  async newPage(){const context=await this.send('Target.createBrowserContext');const target=await this.send('Target.createTarget',{url:'about:blank',browserContextId:context.browserContextId});const attached=await this.send('Target.attachToTarget',{targetId:target.targetId,flatten:true});if(!attached.sessionId)throw new Error('LIGHTPANDA_TAB_UNAVAILABLE');this.sessionId=attached.sessionId;await this.send('Page.enable');await this.send('Runtime.enable');}
  async evaluate<T>(expression:string):Promise<T>{const result=await this.send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(result.exceptionDetails)throw new Error('LIGHTPANDA_PAGE_SCRIPT_FAILED');return result.result?.value as T;}
  close(){this.socket.close();for(const waiting of this.pending.values())waiting.reject(new Error('LIGHTPANDA_CLOSED'));this.pending.clear();}
}
async function connect(port:number){const deadline=Date.now()+10_000;while(Date.now()<deadline){try{const socket=new WebSocket(`ws://127.0.0.1:${port}/`);await new Promise<void>((resolve,reject)=>{socket.addEventListener('open',()=>resolve(),{once:true});socket.addEventListener('error',()=>reject(new Error('LIGHTPANDA_CONNECT_FAILED')),{once:true});});const cdp=new Cdp(socket);await cdp.newPage();return cdp;}catch{await pause(150);}}throw new Error('LIGHTPANDA_START_FAILED');}
async function withLightpanda<T>(cookieFile:string,run:(cdp:Cdp)=>Promise<T>):Promise<T>{
  const port=await freePort();const child:ChildProcess=spawn('lightpanda',['serve','--host','127.0.0.1','--port',String(port),'--cookie',cookieFile,'--disable-metrics'],{stdio:['ignore','ignore','pipe'],env:{...process.env,LIGHTPANDA_DISABLE_TELEMETRY:'true'}});
  let error='';child.stderr?.on('data',chunk=>{error=(error+String(chunk)).slice(-1000);});let cdp:Cdp|undefined;
  try{cdp=await connect(port);return await run(cdp);}catch(cause){if((cause as Error).message==='LIGHTPANDA_START_FAILED'&&error.includes('Cookie'))throw new Error('LIGHTPANDA_COOKIE_LOAD_FAILED');throw cause;}finally{cdp?.close();child.kill('SIGTERM');}
}
async function navigate(cdp:Cdp){await cdp.send('Page.navigate',{url:'https://www.tiktok.com/tiktokstudio/upload'});for(let i=0;i<40;i++){const state=await cdp.evaluate<{url:string;fileInput:boolean;login:boolean;captcha:boolean;accountLinks:string[]}>(`({url:location.href,fileInput:!!document.querySelector('input[type="file"]'),login:/\\/login(?:\\/|$)/.test(location.pathname)||!!document.querySelector('input[type="password"]'),captcha:/captcha|verify you are human/i.test(document.body?.innerText||''),accountLinks:Array.from(document.querySelectorAll('a[href*="/@"]')).map(a=>a.getAttribute('href')||'').slice(0,10)})`);if(state.login||state.captcha||state.fileInput)return state;await pause(500);}throw new Error('TIKTOK_UPLOAD_PAGE_UNAVAILABLE');}
function assertSession(state:Awaited<ReturnType<typeof navigate>>,account?:string){if(state.login)throw new Error('TIKTOK_LOGIN_REQUIRED');if(state.captcha)throw new Error('TIKTOK_CAPTCHA_REQUIRED');if(!state.fileInput)throw new Error('TIKTOK_UPLOAD_CONTROL_MISSING');if(account&&!state.accountLinks.some(link=>link.toLowerCase().includes(`/@${account.toLowerCase()}`)))throw new Error('TIKTOK_ACCOUNT_NOT_VERIFIED');}
export async function checkTikTokSession(cookieFile:string,account?:string){await checkedCookieFile(cookieFile);return withLightpanda(cookieFile,async cdp=>{const state=await navigate(cdp);const accountVerified=account?state.accountLinks.some(link=>link.toLowerCase().includes(`/@${normalizeAccount(account).toLowerCase()}`)):null;return {ready:state.fileInput&&!state.login&&!state.captcha&&accountVerified!==false,accountVerified,url:state.url,reason:state.login?'TIKTOK_LOGIN_REQUIRED':state.captcha?'TIKTOK_CAPTCHA_REQUIRED':!state.fileInput?'TIKTOK_UPLOAD_CONTROL_MISSING':accountVerified===false?'TIKTOK_ACCOUNT_NOT_VERIFIED':'OK'};});}
async function setFile(cdp:Cdp,file:string){const document=await cdp.send('DOM.getDocument',{depth:-1});const input=await cdp.send('DOM.querySelector',{nodeId:document.root.nodeId,selector:'input[type="file"]'});if(!input.nodeId)throw new Error('TIKTOK_UPLOAD_CONTROL_MISSING');await cdp.send('DOM.setFileInputFiles',{nodeId:input.nodeId,files:[file]});}
async function fillCaption(cdp:Cdp,caption:string){const result=await cdp.evaluate<string>(`(()=>{const options=[...document.querySelectorAll('div[contenteditable="true"],textarea')].filter(e=>e.getBoundingClientRect().width>0&&e.getBoundingClientRect().height>0);if(options.length!==1)return 'CAPTION_FIELD_AMBIGUOUS';const el=options[0];el.focus();if(el instanceof HTMLTextAreaElement){const setter=Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value')?.set;setter?.call(el,${JSON.stringify(caption)});}else el.textContent=${JSON.stringify(caption)};el.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText',data:${JSON.stringify(caption)}}));el.dispatchEvent(new Event('change',{bubbles:true}));return (el instanceof HTMLTextAreaElement?el.value:el.textContent)===${JSON.stringify(caption)}?'OK':'CAPTION_NOT_SET';})()`);if(result!=='OK')throw new Error(`TIKTOK_${result}`);}
async function selectPrivate(cdp:Cdp){const result=await cdp.evaluate<string>(`(()=>{const controls=[...document.querySelectorAll('button,[role="button"],[role="radio"]')].filter(e=>e.getBoundingClientRect().width>0&&e.getBoundingClientRect().height>0);const menu=controls.filter(e=>/^(everyone|friends|followers|public|mọi người|bạn bè)$/i.test((e.textContent||'').trim()));if(menu.length===1)menu[0].click();const options=[...document.querySelectorAll('button,[role="option"],[role="radio"],[role="menuitem"]')].filter(e=>e.getBoundingClientRect().width>0&&e.getBoundingClientRect().height>0&&/^(only me|private|chỉ mình tôi|riêng tư)$/i.test((e.textContent||'').trim()));if(options.length!==1)return 'PRIVATE_OPTION_NOT_UNIQUE';options[0].click();return 'OK';})()`);if(result!=='OK')throw new Error(`TIKTOK_${result}`);await pause(300);const selected=await cdp.evaluate<boolean>(`(()=>{const options=[...document.querySelectorAll('button,[role="radio"],[role="option"]')];return options.some(e=>/^(only me|private|chỉ mình tôi|riêng tư)$/i.test((e.textContent||'').trim())&&(e.getAttribute('aria-checked')==='true'||e.getAttribute('aria-selected')==='true'||e.getAttribute('data-state')==='checked'));})()`);if(!selected)throw new Error('TIKTOK_PRIVATE_NOT_VERIFIED');}
async function postButton(cdp:Cdp){return cdp.evaluate<number>(`(()=>[...document.querySelectorAll('button')].filter(e=>e.getBoundingClientRect().width>0&&e.getBoundingClientRect().height>0&&!e.disabled&&/^(post|đăng)$/i.test((e.textContent||'').trim())).length)()`);}
async function waitForPostButton(cdp:Cdp){for(let i=0;i<180;i++){if(await postButton(cdp)===1)return;const blocked=await cdp.evaluate<string>(`(()=>{const text=document.body?.innerText||'';if(/captcha|verify you are human/i.test(text))return 'TIKTOK_CAPTCHA_REQUIRED';if(/\\/login(?:\\/|$)/.test(location.pathname)||document.querySelector('input[type="password"]'))return 'TIKTOK_LOGIN_REQUIRED';return '';})()`);if(blocked)throw new Error(blocked);await pause(1000);}throw new Error('TIKTOK_POST_BUTTON_NOT_READY');}
async function observeNewPost(cdp:Cdp,account:string,baseline:Set<string>){for(let i=0;i<60;i++){const links=await cdp.evaluate<string[]>(`(()=>[location.href,...document.querySelectorAll('a[href]')].map(e=>typeof e==='string'?e:e.href).filter(Boolean))()`);const found=links.find(link=>{try{const url=new URL(link);const segments=url.pathname.split('/').filter(Boolean);return (url.hostname==='tiktok.com'||url.hostname.endsWith('.tiktok.com'))&&segments.length===3&&segments[0].toLowerCase()===`@${account.toLowerCase()}`&&segments[1]==='video'&&/^\d+$/.test(segments[2])&&!baseline.has(url.href);}catch{return false;}});if(found)return found;await pause(1000);}return null;}
async function verifyInStudio(cdp:Cdp,postUrl:string){await cdp.send('Page.navigate',{url:'https://www.tiktok.com/tiktokstudio/content'});const expected=new URL(postUrl).pathname;for(let i=0;i<30;i++){const state=await cdp.evaluate<{url:string;links:string[];login:boolean;captcha:boolean}>(`({url:location.href,links:[...document.querySelectorAll('a[href]')].map(a=>a.href),login:/\\/login(?:\\/|$)/.test(location.pathname)||!!document.querySelector('input[type="password"]'),captcha:/captcha|verify you are human/i.test(document.body?.innerText||'')})`);if(state.login||state.captcha)break;if(state.url.includes('/tiktokstudio/content')&&state.links.some(link=>{try{return new URL(link).pathname===expected;}catch{return false;}}))return true;await pause(1000);}return false;}
export async function publishTikTokPost(root:string,approvalCode:string,cookieFile:string){
  await checkedCookieFile(cookieFile);const record=await load(root,approvalCode);if(record.status!=='approved'||!record.approvedAt)throw new Error('TIKTOK_POST_NOT_APPROVED');const video=await checkedRender(root);if(video.sha256!==record.sha256||video.bytes!==record.bytes||video.state.workflowId!==record.workflowId)throw new Error('TIKTOK_VIDEO_CHANGED');
  const lockPath=`${recordPath(root,approvalCode)}.lock`;const lock=await open(lockPath,'wx',0o600).catch(()=>{throw new Error('TIKTOK_POST_IN_PROGRESS');});let submitted=false;
  try{
    return await withLightpanda(cookieFile,async cdp=>{
      const session=await navigate(cdp);assertSession(session,record.account);
      const baseline=new Set(await cdp.evaluate<string[]>(`(()=>[location.href,...document.querySelectorAll('a[href]')].map(e=>typeof e==='string'?e:e.href).filter(Boolean))()`));
      await setFile(cdp,video.file);await pause(1000);await fillCaption(cdp,record.caption);await selectPrivate(cdp);
      await waitForPostButton(cdp);
      record.status='submitting';record.attemptedAt=new Date().toISOString();await save(root,record);submitted=true;
      const clicked=await cdp.evaluate<boolean>(`(()=>{const buttons=[...document.querySelectorAll('button')].filter(e=>e.getBoundingClientRect().width>0&&e.getBoundingClientRect().height>0&&!e.disabled&&/^(post|đăng)$/i.test((e.textContent||'').trim()));if(buttons.length!==1)return false;buttons[0].click();return true;})()`);
      if(!clicked)throw new Error('TIKTOK_POST_CLICK_UNCERTAIN');
      const postUrl=await observeNewPost(cdp,record.account,baseline);record.postUrl=postUrl;const verified=postUrl?await verifyInStudio(cdp,postUrl):false;record.status=verified?'verified':'outcome_unknown';record.reason=verified?null:postUrl?'TIKTOK_POST_NOT_CONFIRMED_IN_STUDIO':'TIKTOK_POST_URL_NOT_OBSERVED';return save(root,record);
    });
  }catch(error){record.status=submitted?'outcome_unknown':'action_required';record.reason=error instanceof Error?error.message:String(error);await save(root,record);throw error;}finally{await lock.close();await unlink(lockPath).catch(()=>{});}
}
