import path from 'node:path';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {home} from './protocol.ts';
import {loadWorkflow,validateScript} from './workflow.ts';
import {workflowToken} from './license-api.ts';

const run=promisify(execFile),keychainService='com.windistudio.voice-api',keychainAccount='Windi Voice',configFile=path.join(home,'client.json'),defaultApi='https://windistudio.app';
async function config(){try{return JSON.parse(await readFile(configFile,'utf8')) as {apiUrl?:string};}catch{return {};}}
async function saveConfig(apiUrl:string){await mkdir(home,{recursive:true,mode:0o700});await writeFile(configFile,`${JSON.stringify({apiUrl},null,2)}\n`,{mode:0o600});}
async function token(){try{return (await run('/usr/bin/security',['find-generic-password','-a',keychainAccount,'-s',keychainService,'-w'])).stdout.trim();}catch{try{return await workflowToken();}catch{throw new Error('VOICE_LOGIN_REQUIRED: kích hoạt Video Workflow hoặc chạy `windi login`.');}}}
async function apiUrl(){return (await config()).apiUrl||process.env.WINDI_API_URL||defaultApi;}
async function callApi(endpoint:string,init:RequestInit={}){const secret=await token();const headers=new Headers(init.headers);headers.set('Authorization',`Bearer ${secret}`);const response=await fetch(`${await apiUrl()}${endpoint}`,{...init,headers});const contentType=response.headers.get('content-type')||'';const body=contentType.includes('json')?await response.json():await response.arrayBuffer();if(!response.ok)throw new Error((body as {error?:string})?.error||`VOICE_API_${response.status}`);return body;}

export async function loginVoice(secret:string,requestedApiUrl?:string){if(!/^windi_voice_[A-Za-z0-9_-]{32,}$/.test(secret))throw new Error('INVALID_WINDI_VOICE_TOKEN');const base=(requestedApiUrl||process.env.WINDI_API_URL||defaultApi).replace(/\/$/,'');const response=await fetch(`${base}/api/v1/voice/voices`,{headers:{Authorization:`Bearer ${secret}`}});if(!response.ok){const body=await response.json().catch(()=>({})) as {error?:string};throw new Error(body.error||`VOICE_API_${response.status}`);}const result=await response.json() as {data?:unknown[]};await run('/usr/bin/security',['add-generic-password','-U','-a',keychainAccount,'-s',keychainService,'-w',secret]);await saveConfig(base);return {connected:true,apiUrl:base,voices:result.data?.length??0};}

export async function listWorkflowVoices(){const result=await callApi('/api/v1/voice/voices') as {data?:Array<{id:string;name:string;language?:string;kind?:string}>};return result.data??[];}
export async function workflowVoiceReceipt(id:string){
  const result=await callApi(`/api/v1/voice/generations/${encodeURIComponent(id)}`) as {id:string;status:string;voice_name:string;credits:number;created_at:string};
  return {id:result.id,status:result.status,voiceName:result.voice_name,credits:result.credits,createdAt:result.created_at};
}

function captionsFromWords(value:{words?:unknown[];start?:unknown[];end?:unknown[]}){const count=Math.min(value.words?.length??0,value.start?.length??0,value.end?.length??0),captions=[];for(let index=0;index<count;index++){const text=value.words?.[index],start=Number(value.start?.[index]),end=Number(value.end?.[index]);if(typeof text==='string'&&Number.isFinite(start)&&Number.isFinite(end)&&end>start)captions.push({text,startMs:Math.round(start*1000),endMs:Math.round(end*1000),timestampMs:Math.round(start*1000),confidence:null});}if(!captions.length)throw new Error('VOICE_API_TIMESTAMPS_EMPTY');return captions;}
export async function generateWorkflowVoice(projectRoot:string,voiceId:string,speed=1,segment?:{text:string;id:string}){const state=await loadWorkflow(projectRoot);if(state.approvals.script.status!=='approved'||!state.current.script)throw new Error('SCRIPT_APPROVAL_REQUIRED');const script=validateScript(JSON.parse(await readFile(path.join(projectRoot,state.current.script),'utf8')));const text=segment?.text??script.beats.map(beat=>beat.voiceOver.trim()).join('\n\n');const key=createHash('sha256').update(`${state.workflowId}:${script.version}:${segment?.id||"full"}:${voiceId}:${speed}:${text}`).digest('hex');const generation=await callApi('/api/v1/voice/generations',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':key},body:JSON.stringify({text,voice_id:voiceId,language:script.language,speed})}) as {id:string;status:string};if(generation.status!=='ready')throw new Error(`VOICE_JOB_${generation.status.toUpperCase()}: ${generation.id}`);const detail=await callApi(`/api/v1/voice/generations/${generation.id}?include=timestamps`) as {timestamps?:{words?:unknown[];start?:unknown[];end?:unknown[]}};const audio=await callApi(`/api/v1/voice/generations/${generation.id}/audio`) as ArrayBuffer;const voiceDir=path.join(projectRoot,'windi','voice'),timingDir=path.join(projectRoot,'windi','timing');await mkdir(voiceDir,{recursive:true,mode:0o700});await mkdir(timingDir,{recursive:true,mode:0o700});const audioFile=path.join(voiceDir,`${generation.id}.mp3`),captionsFile=path.join(timingDir,`captions-${generation.id}.json`);await writeFile(audioFile,Buffer.from(audio),{mode:0o600});await writeFile(captionsFile,`${JSON.stringify(captionsFromWords(detail.timestamps||{}),null,2)}\n`,{mode:0o600});return {id:generation.id,audio:audioFile,captions:captionsFile};}
